language: node_js
node_js:
  - "8"
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn install
  - yarn global add gh-pages

script:
  - yarn build

cache:
  yarn: true

deploy:
  provider: pages
  target-branch: gh-pages
  local-dir: build/
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
