version: 2

jobs:
  test:
    machine:
      enabled: true
      image: circleci/classic:edge
      docker_layer_caching: true

    working_directory: /home/circleci/project

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: ./.circleci/install-yarn.sh

      - run: source /opt/circleci/.nvm/nvm.sh && yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: source /opt/circleci/.nvm/nvm.sh && yarn test
      - run: source /opt/circleci/.nvm/nvm.sh && yarn build

      # e2e
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker pull oasisdex/localnode:ba221c672ed073817c3742794d9f47bb4e6c6c3e
      - run: docker run -d -p 8545:8545 oasisdex/localnode:ba221c672ed073817c3742794d9f47bb4e6c6c3e
      - run: ./.circleci/wait-for-it.sh localhost:8545 -t 10 && sleep 10 # @todo this needs to be improved. Wait for it doesnt really work since contract deployment happens later
      - run: source /opt/circleci/.nvm/nvm.sh && ./cypress/scripts/run-e2e.sh

  deploy_stage:
    docker:
      - image: circleci/node:8.11.2-stretch
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn deploy:stage

workflows:
  version: 2

  mainflow:
    jobs:
      - test
      - deploy_stage:
          requires:
            - test
          filters:
            branches:
              only: release/simpson
